### ISSUE TITLE
Cannot close application (Linux)

### ISSUE THREAD

**Issue by rchastain** [wp-xyz/Oscilloscope#4]
Hello! Congratulations for this beautiful project. I compiled and tested the application on Linux 64. It works well, but I cannot close the application. When I click on the close button, the application freezes.
Regards.
Roland

**Comment by wp-xyz** [comment]
I just checked on Linux 64bit, and I do not see such an issue. Also FredvS who is currently working on integrating the UOS library did not report  anything like that.

What exactly are you doing? Please give precise steps to reproduce.

**Comment by rchastain** [comment]
Thank you for your answer.

I simply execute the application, and immediately after I try to close the application, by clicking on the close button of the window. The window becomes white and I get a message from the OS saying that the application no longer answers.

It's the same behaviour when I start the application from the IDE, or when I start it directly.

I will try on another computer, where I have another Linux distribution.

**Comment by wp-xyz** [comment]
> I simply execute the application

That's the intersting part. The program contains several modules and I must know which ones you use. At first, delete the config file ("Oscilloscope.cfg"), it is in folder .config of your home directory; this way your application starts with default parameters. Then run the program and close it immediately - does the error occur? If make small changes and close again, until the big happens. Tell me what exactly you must do until the issue occurs. You maybe should send the config file.

**Comment by rchastain** [comment]
After I deleted the config file, the error occurs.

**Comment by wp-xyz** [comment]
So, after having deleted the cfg file, you just started the program and then immediately closed it again, and the error occured. I've checked this case many times and I do not see such an error...

Just one idea. I am not sure how the program behaves on Linux when the BASS library is missing or has the wrong bitness. Are you sure that you have the file libbass.so somewhere in your system so that it can be found (unlike Windows it is not enough to copy it into the exe folder, AFAIK). And are you sure that it is the 64-bit version of the library?

**Comment by rchastain** [comment]
Indeed, BASS was missing. After I installed it, no more error.

Thank you for your help.
